language: node_js
node_js:
  - '10'
  - '12'
  - '14'
after_success:
  - hash npx 2> /dev/null && npx codecov
deploy:
  provider: npm
  email: remcohaszing@gmail.com
  api_key: $NPM_ACCESS_TOKEN
  on:
    tags: true
    node: '10'
